### ISSUE TITLE
Feature Request: EKS support 

### ISSUE THREAD

**Issue by msebbar** [aws/aws-step-functions-data-science-sdk-python#106]
AWS Stepfunctions now support AWS EKS. It would be very helpful to have this service implemented into the SDK.

**Comment by wong-a** [comment]
Thanks for the feature request! 

To clarify, you're just looking for a service integration `Step` like we have for DynamoDB, SQS, SNS, and EMR, right? https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/services.html

If you (or anyone) is up for it, contributions are more than welcome 😄 . Here's an example of adding EMR Steps: https://github.com/aws/aws-step-functions-data-science-sdk-python/pull/12/files

Until then, you should be able to use any service integration not implemented in the SDK by using the base [`Task` class](https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/states.html#stepfunctions.steps.states.Task) and providing the parameters and resource ARN of the service integration yourself.

**Comment by ca-nguyen** [comment]
Support for Amazon EKS will be included in next release with #156
