### ISSUE TITLE
SDK Feature enhancement : Support for AWS Glue DataBrew in the SDK

### ISSUE THREAD

**Issue by nsankar** [aws/aws-step-functions-data-science-sdk-python#112]
AWS news update indicates Glue Databrew now supports stepfunctions.
https://aws.amazon.com/about-aws/whats-new/2021/01/aws-step-functions-support-aws-glue-databrew-jobs-data-analytics-machine-learning-workflows/

Hope this feature will be added in this SDK soon.

**Comment by wong-a** [comment]
Thanks for the feature request!

If you (or anyone) is up for it, contributions are more than welcome 😄 . Here's an example of adding EMR Steps: https://github.com/aws/aws-step-functions-data-science-sdk-python/pull/12/files

Until then, you should be able to use any service integration not implemented in the SDK by using the base [`Task` class](https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/states.html#stepfunctions.steps.states.Task) and providing the parameters and resource ARN of the service integration yourself.
