### ISSUE TITLE
Make sagemaker an feature install

### ISSUE THREAD

**Issue by milesgranger** [aws/aws-step-functions-data-science-sdk-python#116]
`pip install stepfunctions[sagemaker]`

Why? :thinking: 
---
Because `sagemaker` comes with some [not-so-light dependencies](https://github.com/aws/sagemaker-python-sdk/blob/54fd5f113dd60d08ee2e752715d2b8d43cd50631/setup.py#L35). And in situations where the sagemaker module isn't used, we're taking up some valuable space.

ie. After installing we have things like `scipy`, `numpy` which aren't needed if one is not using the sagemaker module.

```
✦ ❯ du -h --max-depth=1  venv/lib/python3.7/site-packages/ | sort -hr
240M	venv/lib/python3.7/site-packages/
65M	venv/lib/python3.7/site-packages/scipy
56M	venv/lib/python3.7/site-packages/botocore
33M	venv/lib/python3.7/site-packages/numpy.libs
30M	venv/lib/python3.7/site-packages/scipy.libs
28M	venv/lib/python3.7/site-packages/numpy
```

**Comment by wong-a** [comment]
Resolving in favour of https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/184
