### ISSUE TITLE
Latest Step Functions choice operators are not available in 1.1.2 release

### ISSUE THREAD

**Issue by anatoly-scherbakov** [aws/aws-step-functions-data-science-sdk-python#121]
## Version

```
>>> import stepfunctions
>>> stepfunctions.__version__
'1.1.2'
```

installed from pypi.

## Expected

In [this commit](https://github.com/aws/aws-step-functions-data-science-sdk-python/commit/16177d781f204914cf58cf8f5106fb3fbb9d6660) from 22 Sep 2020, new comparators were added to `stepfunctions`, including `IsPresent`. On 24 Sep 2020, the 1.1.2 release was published to PyPI. So I expected to see the new comparators available there. But,

## What actually happens

is this:

```python
>>> from stepfunctions.steps import ChoiceRule
>>> ChoiceRule.IsPresent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'ChoiceRule' has no attribute 'IsPresent'
```

perhaps it would be possible to publish a new release with these features included? Thank you!

**Comment by wong-a** [comment]
Hi @anatoly-scherbakov, as you noted, https://github.com/aws/aws-step-functions-data-science-sdk-python/pull/88 adds support for the new choice operators but is not yet released. We're working on a v2 release that will include this! Stay tuned.

#108

**Comment by shivlaks** [comment]
@anatoly-scherbakov - `v2` has been [released](https://pypi.org/project/stepfunctions/) and includes support for the new choice operators.

Take a look at the [release notes](https://github.com/aws/aws-step-functions-data-science-sdk-python/releases/tag/v2.0.0) for details on upgrading and breaking changes in `v2.0.0`.

Resolving this issue, feel free to reopen if you have any outstanding questions!
