### ISSUE TITLE
Feature Request : Integration with Amazon EventBridge

### ISSUE THREAD

**Issue by mnaginen** [aws/aws-step-functions-data-science-sdk-python#141]
Step Functions integrates with Amazon EventBridge to provide a solution for producing events during a workflow. If we can extend this functionality to the DS SDK, as this native integration with EB is being asked by customers. It could contribute a lot of value to the customers.

Are there any plans in the pipeline to support this?

**Comment by wong-a** [comment]
You're referring to the EventBridge service integration right - to add a step that calls PutEvents? https://docs.aws.amazon.com/step-functions/latest/dg/connect-eventbridge.html

Step Functions also emits events to EventBridge when the execution starts or finishes. https://docs.aws.amazon.com/step-functions/latest/dg/cw-events.html

**Comment by mnaginen** [comment]
Yes I am referring to the EventBridge Service integration that we recently launched last month - https://aws.amazon.com/blogs/compute/introducing-the-amazon-eventbridge-service-integration-for-aws-step-functions/
Can the DS SDK extend to support this feature - https://aws-step-functions-data-science-sdk.readthedocs.io/en/stable/

**Comment by wong-a** [comment]
Makes sense. The SDK can definitely include this integration. We'll prioritize this based on number of requests/+1s. You're more than welcome to make a contribution too!

You can see how other service integrations are implemented here: 
https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/main/src/stepfunctions/steps/service.py#L210-L247

With corresponding unit tests:
https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/main/tests/unit/test_service_steps.py#L63-L99
