### ISSUE TITLE
adding a catch state to a workflow

### ISSUE THREAD

**Issue by vincentclaes** [aws/aws-step-functions-data-science-sdk-python#145]
I would like to trigger a notification whenever there is an error on my workflow.
there is a great example using classic stepfunctions JSON here: https://dashbird.io/blog/aws-step-functions-error-handling/

![](https://dashbird.io/wp-content/uploads/2020/11/Screenshot-2020-11-30-at-12.10.22.png)

I have been trying for a while now, but I was unsuccessful in implementing a `Catch` state that is triggered whenever there is an error on the workflow. I couldn't find any examples online or on github. Is it possible to share a small example on how to implement this?

thanks a lot.

great work what you guys are doing btw!!

**Comment by vincentclaes** [comment]
OMG; 5 minutes after writing this issue I have found a solution.

```
from stepfunctions import steps
from stepfunctions.workflow import Workflow
from stepfunctions.steps.states import Parallel
from stepfunctions.steps import Catch
from stepfunctions.steps.service import SnsPublishStep
import uuid

sns = SnsPublishStep("send-sns", comment="something went wrong", parameters={"TopicArn":"arn:aws:sns:some-arn"})
catch_error = Catch(error_equals=["States.ALL"], next_step=sns)

chain_of_steps = steps.Chain([step1, step2, step3])
workflow_notification = Parallel(state_id="workflow-with-notification")
workflow_notification .add_branch(chain_of_steps )
workflow_notification .add_catch(catch_error)

w = Workflow(
            name="some-unique-name-{}".format(uuid.uuid4().hex),
            definition=workflow_notification ,
            role="arn:aws:iam:::role/some-role"
        )
w.render_graph()
w.execute()

```

**Comment by wong-a** [comment]
@vincentclaes That looks about right. You can use a `Parallel` state to implement a global catch as the blog suggests. Any Anything we can help with regarding this topic?

In general, the mapping between Amazon States Language JSON and the step classes in this SDK are pretty transparent. We just expose the fields from a Python class that gets converted to JSON.

**Comment by vincentclaes** [comment]
thanks @wong-a, i think i'm good :)
