### ISSUE TITLE
Possible to re-attach a running execution using execution_arn?

### ISSUE THREAD

**Issue by antje** [aws/aws-step-functions-data-science-sdk-python#19]
Hi, 

is it possible to re-attach a running execution to a workflow using the execution_arn, let's say if my notebook crashes? I've only found a Workflow.[attach()](https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/workflow.html#stepfunctions.workflow.Workflow.attach) in the documentation, no Execution.attach()? 

Thanks!

**Comment by shunjd** [comment]
Hi Antje,

There is no Execution.attach(), you will need to call Workflow.attach() to get a Workflow instance, then use Workflow.[list_executions()](https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/master/src/stepfunctions/workflow/stepfunctions.py#L315) to find your expected execution.

Shunjia
