### ISSUE TITLE
Retry policies with error codes

### ISSUE THREAD

**Issue by rodrick10** [aws/aws-step-functions-data-science-sdk-python#191]
Currently, stepfunctions retry policies only check the error name. 
If the error name is vague and we need to check its cause, there is no way to do that.

### Use Case
Below you can see an example with a sagemaker training job. 
![image](https://user-images.githubusercontent.com/82222517/209653933-ac5cb2a5-c31e-4df2-9925-53cc56c40348.png)

In this example, I want to retry only if there is a "ThrottlingException".  I cannot do it  because the retry policy only looks at the error name, in this case, "SageMaker.AmazonSageMakerException". 

### Proposed Solution
Improve retry and catch policies to also work with the error cause.

This is a :rocket: Feature Request

**Comment by wong-a** [comment]
Closing as this is outside the scope of the Step Functions Data Science SDK. Retrier semantics is part of Amazon States Language.
