### ISSUE TITLE
Does the Step Function Data Science SDK support SageMaker Processing Jobs similar to Batch Transform Jobs?

### ISSUE THREAD

**Issue by cfregly** [aws/aws-step-functions-data-science-sdk-python#20]
cc @shunjd 

I see stepfunctions.steps.sagemaker.TransformStep for [Batch Transform Jobs](https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateTransformJob.html), but I don't see the equivalent for [SageMaker Processing Jobs](https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateProcessingJob.html).  Am I missing something?

If this support doesn't exist, can you suggest a suitable workaround?  Perhaps, we need to invoke a shim Lambda function for now?  

Any idea when support for SageMaker Processing Jobs will be added to the Step Function Data Science SDK?

**Comment by shunjd** [comment]
Hi Chris,

We are currently investigating the options to integrate with the new SageMaker Processing Jobs. The AWS Step Functions (the service) needs to implement this new service integration first, then we can integrate it into the Python SDK.

Shunjia

**Comment by trevor-smith** [comment]
Please keep us updated on this!!  I would love for this feature to exist.  I use processing jobs in my ML workflow and would love to be able to use a step function to control my pipeline instead of using lambda functions that rely on s3 triggers based on a put operation.  Thank you!

**Comment by ARDivekar** [comment]
@shunjd we have a use-case for this. Could you please let us know what would be a timeline for this integration?

**Comment by igoichuk** [comment]
@shunjd I am also interested in the processing step. Is there a way to submit SageMaker processing job using LambdaStep? I assume there should be created a lambda function that submits SageMaker processing jobs.

**Comment by cfregly** [comment]
looking forward to this being released!  looks like the code was just merged.  fingers-crossed.

**Comment by dhawalkp** [comment]
Hi @cfregly Please refer to my new notebook demonstrating the new ProcessingStep here - 
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/step-functions-data-science-sdk/step_functions_mlworkflow_processing/step_functions_mlworkflow_scikit_learn_data_processing_and_model_evaluation.ipynb
