### ISSUE TITLE
I am not able to view the Stepfunction rendition from an Amazon SageMaker Notebook

### ISSUE THREAD

**Issue by asahalyft** [aws/aws-step-functions-data-science-sdk-python#29]
For Context I am following the article https://github.com/juliensimon/amazon-sagemaker-examples/blob/master/step-functions-data-science-sdk/hello_world_workflow/hello_world_workflow.ipynb  from Julien Simon of AWS

For context this is the corresponding video link https://youtu.be/0kMdOi69tjQ?t=502  where the author calls the render graph method on the jupyter notebook and he is able to see the graph

basic_workflow_execution.render_progress() doest not render the graph in the Amazon SageMaker Notebook but I can see the rendered graph in the AWS Step Functions console.
<img width="1214" alt="jupyter-notebook" src="https://user-images.githubusercontent.com/48966647/74212952-c0418900-4c4b-11ea-9704-25543a5f8f20.png">

**Comment by vaib-amz** [comment]
Hi Anindya,

Looking at the screenshot posted in the issue, it looks like you might be using JupyterLab as your notebook environment. The graph visualizations provided by the Step Functions Data Science SDK are supported only on the standard Jupyter environment at present.

If you face any issues with the graph visualizations in the standard Jupyter environment, please let us know.

Vaib

**Comment by asahalyft** [comment]
Ah, I see. That's indeed. It's working in notebook but not in Jupyter Lab.
