### ISSUE TITLE
Can't seem to specify `inference.py` and `requirements.txt` with TrainingPipeline - only `model_fn`

### ISSUE THREAD

**Issue by cfregly** [aws/aws-step-functions-data-science-sdk-python#44]
Is there a way to specify `inference.py` and `requirements.txt` with `TrainingPipeline` for the deploy step?

I only see a `model_fn()` mentioned, but I need to perform request-level transformations.  And, actually, how is `model_fn()` enough?  What is the format of the data coming in?

I haven't actually tested the end-to-end [PyTorch/MNIST example](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/step-functions-data-science-sdk/training_pipeline_pytorch_mnist/mnist.py), but I don't understand how `model_fn()` would work, now that I look at the example closer.  Can you help me understand?

I pulled down the deployed model.tar.gz inference code but i don't see the equivalent of an inference.py in the bundle.

And are there any TensorFlow examples?  I only see PyTorch at the moment.

Thanks!

**Comment by shunjd** [comment]
Hi Chris, 

`model_fn` is explained [here](https://sagemaker.readthedocs.io/en/stable/using_sklearn.html#load-a-model).

> Before a model can be served, it must be loaded. The SageMaker Scikit-learn model server loads your model by invoking a model_fn function that you must provide in your script. The model_fn should have the following signature:

We have an example in the integration test for PyTorch, but it should be the same for TensorFlow.

https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/21d6aa19b6aa73bb6a25490e1cdf0257ac44f815/tests/data/pytorch_mnist/mnist.py

**Comment by cfregly** [comment]
Good info @shunjd .  I understand `model_fn()`.   my question is more around the request-level functions like input_fn(), output_fn() as described [here](https://sagemaker.readthedocs.io/en/stable/using_sklearn.html#serve-a-model)

How do we specify those?  And how do the existing samples work without specifying `input_fn()` and `output_fn()`.  I assume they're just convert lists of floats into numpy arrays.  However, if i want to do more-complex transformations on my requests/responses - where would i do those?

**Comment by shunjd** [comment]
I think you are right, if you provide `input_fn()` and `output_fn()` in the script, then sagemaker endpoint will use your script to transform the intput/output.

**Comment by shunjd** [comment]
And also, sagemaker has a new [processing job](https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_processing.html) which is a separate process to allow you put your feature transformation logic. (This is not integrated with the data science SDK yet.)

**Comment by cfregly** [comment]
ok, i'll try `input_fn()` and `output_fn()` and update you.

and yes, i'm very much waiting for the ProcessingJobs integration per this issue https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/20
