### ISSUE TITLE
Cannot output null value in ResultPath

### ISSUE THREAD

**Issue by shunjd** [aws/aws-step-functions-data-science-sdk-python#45]
We cannot output the following JSON definition even if result_path is None.

```
{
  "Type": "Parallel",
  "ResultPath": null
}
```

If `result_path` is specified explicitly, user should expect to have it in the final statemachine definition.

```
from stepfunctions import steps

p = steps.Parallel('test', result_path=None)
assert 'ResultPath' in p.to_dict()
```

**Comment by tuliocasagrande** [comment]
Hey @shunjd, I hope you're doing great man.

I faced the same behavior yesterday with a `steps.Task`, so I submitted #48 that I think fixes this error for any state type.

Let me know what you think.
Thanks!
