### ISSUE TITLE
Allow Workflow.create() to update workflow

### ISSUE THREAD

**Issue by tuliocasagrande** [aws/aws-step-functions-data-science-sdk-python#46]
Hey guys,

One use case I believe is very common when using notebooks is to modify some cells and re-run stuff, but the process to update an existing workflow with the SDK requires additional steps.

To explain this, consider these two screenshots:

Here, I executed these cells for the first time and effectively created the workflow called `MyWorkflow_Simple`:
![image](https://user-images.githubusercontent.com/1420513/81248176-298a2b80-8ff2-11ea-8399-322edf9b8877.png)

However, during development I added a new step `second_step` (consider this may occur several times either by adding new steps or modifying existing ones). The problem now is the workflow already exists and I couldn't override/update it:
![image](https://user-images.githubusercontent.com/1420513/81248486-cbaa1380-8ff2-11ea-96fc-90a0474fdcdb.png)

Of course later I managed to update with attach, but this creates additional cells and complexity in terms of reproducibility:
![image](https://user-images.githubusercontent.com/1420513/81248802-9225d800-8ff3-11ea-8baf-0eeccd8ac5e2.png)

Given this usage, which I believe is very common when dealing with notebooks, my proposal would be to add a new parameter `update` (default to `False`) to Workflow.[create()](https://aws-step-functions-data-science-sdk.readthedocs.io/en/latest/workflow.html#stepfunctions.workflow.Workflow.create) to update/override in a single step.

I can submit a PR if you agree with this approach.
Thank you for reviewing this!

**Comment by shunjd** [comment]
Hi @tuliocasagrande, the reason we don't want to update the workflow inside `create` call is because we want to have the explicit feedback when the workflow exists. However, the `create` call does not yield any error, you can simply put `workflow.update()` after it to perform the update without re-attaching.

**Comment by tuliocasagrande** [comment]
Makes sense. I didn't notice the attach wasn't necessary.
Thanks, @shunjd!
