### ISSUE TITLE
Unable to visualize the workflow

### ISSUE THREAD

**Issue by vikiuvb** [aws/aws-step-functions-data-science-sdk-python#54]
**workflow.render_graph(portrait=False)** is not rendering the graph. Looks like the [JS library](https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/master/src/stepfunctions/workflow/widgets/graph.py#L32) is missing from the source.

**Comment by bobbruno** [comment]
While that is true, many rendering libraries (such as ipython widgets) have provided Jupyter Lab extensions to get them working again. It would be nice to provide such an extension for the Step Functions SDK.

**Comment by wong-a** [comment]
Moving to https://github.com/aws/aws-step-functions-data-science-sdk-python/issues/127
