### ISSUE TITLE
ResultPath is ignored if set to None

### ISSUE THREAD

**Issue by juayu** [aws/aws-step-functions-data-science-sdk-python#57]
This doesn't work. if I set the result_path=None, "ResultPath" won't appear in JSON, so I cannot pass the input as output for a task.

Aren't below test case fail every time?

def test_paths_none_converted_to_null():
    task_state = Task('Task', resource='arn:aws:lambda:us-east-1:1234567890:function:StartLambda',
                      result_path=None,
                      input_path=None,
                      output_path=None)
    assert '"ResultPath": null' in task_state.to_json()
    assert '"InputPath": null' in task_state.to_json()
    assert '"OutputPath": null' in task_state.to_json()

**Comment by shunjd** [comment]
The fix has been published, could you install version 1.0.0.9 and try again?

**Comment by juayu** [comment]
I tried to "!pip install stepfunctions==1.0.0.9" in sagemaker notebook
Then run the test again, still not see "ResultPath": null in the output json
Am I missing anything?

**Comment by shunjd** [comment]
Could you try `pip install -U stepfunctions`?

It works for me, see the code below.
```
>>> from stepfunctions.steps import *
>>> task_state = Task('Task', resource='arn:aws:lambda:us-east-1:1234567890:function:StartLambda',
... result_path=None,
... input_path=None,
... output_path=None)
>>> task_state.to_json()
'{"Resource": "arn:aws:lambda:us-east-1:1234567890:function:StartLambda", "ResultPath": null, "InputPath": null, "OutputPath": null, "Type": "Task", "End": true}'
>>> task_state.to_dict()
{'Resource': 'arn:aws:lambda:us-east-1:1234567890:function:StartLambda', 'ResultPath': None, 'InputPath': None, 'OutputPath': None, 'Type': 'Task', 'End': True}
```

**Comment by juayu** [comment]
It works. Previously it's due to Sagemaker, I had to restart the nodebook instance.
Thanks.
