### ISSUE TITLE
Open source the visualization component?

### ISSUE THREAD

**Issue by soamvasani** [aws/aws-step-functions-data-science-sdk-python#6]
Hi, thanks for releasing this as open source! 

I noticed that the code for visualizing workflow graphs refers to [JS](https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/21d6aa19b6aa73bb6a25490e1cdf0257ac44f815/src/stepfunctions/workflow/widgets/graph.py#L32) and [CSS](https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/21d6aa19b6aa73bb6a25490e1cdf0257ac44f815/src/stepfunctions/workflow/widgets/graph.py#L33) files that aren't open source.

Would it be possible to release those components as open source too?  Or at least relax their license to something other than "all rights reserved"?  Thanks!

**Comment by dan-amz** [comment]
Hi Soamvasani,

Thanks for reaching out.  We hope you find the open source project useful!

I am a PM with the Step Functions team.  We have had internal discussions around open sourcing the workflow graph component.  Can you please help us understand your use-case and how you would benefit from having the workflow graph open sourced?

Thanks,
Dan

**Comment by soamvasani** [comment]
Hi Dan, thanks for your response.  I'm building some developer tools for step functions; i.e. the output of my tool is a step function.  It would be nice to be able to visualize the graph, just as this project does. 

I don't actually need it to be completely open source for my use case -- just documented and usable (e.g. I tried to invoke the minified scripts, but I get some errors that are hard to debug, so it would be easier to have the code.)  Alternatively, an AWS API that returns a graph SVG would work too, thought it seems a bit overkill to have an API for this.

**Comment by dan-amz** [comment]
Hi Soam,

I've created a ticket internally with this request and will get back to you within a week or so with an update.  A downloadable .svg of the workflow image is something that has been widely requested by customers.

Dan

**Comment by soamvasani** [comment]
Thanks, @dan-amz!

**Comment by soamvasani** [comment]
Hi again, @dan-amz :slightly_smiling_face:  Any updates?

**Comment by dan-amz** [comment]
Hi Soam,  Apologies for the delay in my response.  We are continuing to evaluate options for visualization that will cover off the different use-cases required by our customers.  Would you be open to a 1/2 hour conference call to discuss?  If so, please PM me.

Thanks,
Dan

**Comment by soamvasani** [comment]
@dan-amz Yeah, happy to chat! I can't seem to find your contact info here -- my email is soam@cohesion.dev, could you send me an email please?
