### ISSUE TITLE
Model path bug In training pipeline template

### ISSUE THREAD

**Issue by SJWilkinson** [aws/aws-step-functions-data-science-sdk-python#61]
I believe there is a bug in the TrainingPipeline class.

You can recreate the bug by running all cells in this [notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/step-functions-data-science-sdk/training_pipeline_pytorch_mnist/training_pipeline_pytorch_mnist.ipynb ) without making any changes.

When I run this notebook, my Step Function fails at the "Create Model" step with the following exception:

```
Error

SageMaker.AmazonSageMakerException
Cause

Could not find model data at s3://sagemaker-us-west-2-{account-number}/training-pipeline-2020-06-30-00-08-30/models/estimator-training-pipeline-2020-06-30-00-08-39/output/model.tar.gz. (Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: 817d6712-c1d1-4765-b1da-bd61c3c7157d)
```

I looked in to the [code here](https://github.com/aws/aws-step-functions-data-science-sdk-python/blob/master/src/stepfunctions/template/pipeline/train.py) and I think the bug occurs in line 153 in this code snippet:

```
        # Configure the path to model artifact
        inputs[StepId.CreateModel.value]['PrimaryContainer']['ModelDataUrl'] = '{s3_uri}/{job}/output/model.tar.gz'.format(
            s3_uri=inputs[StepId.Train.value]['OutputDataConfig']['S3OutputPath'],
            job=inputs[StepId.Train.value]['TrainingJobName']
        )
```

It looks like the SDK passes the model data uri as the string: '{s3_uri}/{TrainingJobName}/output/model.tar.gz', but in my testing it looks like SageMaker treats the TrainingJobName as a prefix, not the entire job name. SageMaker is appending a unique hash to this prefix, which means the S3 path is no longer correct.

For example, when I last ran the notebook my training job succeeded and stored the model artifacts here:

"S3ModelArtifacts": s3://sagemaker-us-west-2-{account-number}/training-pipeline-2020-06-30-00-08-30/models/estimator-training-pipelin **-2136f0ca-232b-4c66-8487-835d6ad1d153** /output/model.tar.gz

but the execution input that Create Model state takes in was:

"ModelDataUrl": "s3://sagemaker-us-west-2-{account-number}/training-pipeline-2020-06-30-00-08-30/models/estimator-training-pipeline-2020-06-30-00-08-39/output/model.tar.gz"

**Comment by SJWilkinson** [comment]
I ran it again in a new AWS account and I didn't encounter this error. SageMaker isn't treating the job name as a prefix. I tried with different jobName lengths, and that didn't reproduce the error.

**Comment by shunjd** [comment]
I followed your steps trying to reproduce it but I could not find any issues, please feel free to open a new issue when you have any other findings.
