### ISSUE TITLE
Steps classes documentation disappeared from readthedocs.io

### ISSUE THREAD

**Issue by ievgen-goichuk-rft** [aws/aws-step-functions-data-science-sdk-python#62]
Documentation of the various Steps and related classes has disappeared from the documentation web-site. For example, SageMaker related steps:
https://aws-step-functions-data-science-sdk.readthedocs.io/en/stable/sagemaker.html

**Comment by shunjd** [comment]
Thank you, @ievgen-goichuk-rft, we are working on the fix now.

**Comment by shunjd** [comment]
It is fixed by now.
