### ISSUE TITLE
Can't Pass dict Objects as Execution Inputs

### ISSUE THREAD

**Issue by SJWilkinson** [aws/aws-step-functions-data-science-sdk-python#64]
When I try to pass a dict object as an execution input, I receive a ValueError.

Notes to reproduce:

Run [this example notebook](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/step-functions-data-science-sdk/hello_world_workflow) but add a dict input to the workflow with the following cells:

from stepfunctions.inputs import ExecutionInput
execution_input = ExecutionInput(schema={
    'InputDict': dict})`

InputDict = {"Key":"Value"}
type(InputDict)

basic_workflow_execution = basic_workflow.execute(
    inputs={"InputDict": InputDict})

When I run the execute method I receive the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-24d0e9277bef> in <module>
      1 basic_workflow_execution = basic_workflow.execute(
----> 2     inputs={"InputDict": InputDict})

~/anaconda3/envs/python3/lib/python3.6/site-packages/stepfunctions/workflow/stepfunctions.py in execute(self, name, inputs)
    285             validation_result = self.workflow_input.validate(inputs)
    286             if validation_result.valid is False:
--> 287                 raise ValueError("Expected run input with the schema: {}".format(self.workflow_input.get_schema_as_json()))
    288 
    289         if self.state_machine_arn is None:

ValueError: Expected run input with the schema: {"InputDict": "dict"}

---------------------------------------------------------------------------

I tried passing in the same dictionairy to the created Step Functions directly through the console and it works:

![image](https://user-images.githubusercontent.com/31523916/87464760-83960700-c5c8-11ea-9528-4bb08f3bad43.png)

**Comment by ca-nguyen** [comment]
Hi @SJWilkinson 

What version of stepfunctions are you using? Are you still experiencing the issue?

I tested out a simple example with a Pass state, using the same execution input format, but did not get the same exception. The following example ran successfully (v2.2.0):

```
from stepfunctions.inputs import ExecutionInput, StepInput
execution_input = ExecutionInput()

execution_input = ExecutionInput(schema={
'InputDict': dict})

pass_state = Pass(
    'PassState',
    parameters={
        'ParamA': execution_input['InputDict']
})


basic_workflow = Workflow(
    name="PassStateMachineExample",
    definition=pass_state,
    role=workflow_execution_role
)
basic_workflow.create()

input_dict = {"Key":"Value"}
basic_workflow_execution = basic_workflow.execute(inputs={"InputDict": input_dict})
```

**Comment by ca-nguyen** [comment]
Confirmed that the above example also works in following versions, which were available at the time the issue was opened:
- v1.0.0.7
- v1.0.0.8
- v1.0.0.9

Closing this issue as it is possible to pass a `dict` as ExecutionInput
Please reopen if the issue reoccurs
