### ISSUE TITLE
Tensorflow estimator script mode not working if we pass HyperParameters as part of TrainingStep

### ISSUE THREAD

**Issue by Axe129** [aws/aws-step-functions-data-science-sdk-python#72]
Hello,

I was trying to use Tensorflow estimator in script mode and I was trying to pass the hyper-parameters as part of `stepfunctions.steps.TrainingStep` as follows: 
<img width="752" alt="Screenshot 2020-08-04 at 6 22 01 PM" src="https://user-images.githubusercontent.com/12937657/89296024-7330f380-d67f-11ea-8475-69c305a90be8.png">

But, the training job failed with the following error
<img width="960" alt="Screenshot 2020-08-04 at 6 11 50 PM" src="https://user-images.githubusercontent.com/12937657/89295023-fa7d6780-d67d-11ea-94ec-0867d003a39b.png">

Upon investigation I found out that other hyper-parameters that the estimator attaches on its own were not going (ex - 'sagemaker_program', 'sagemaker_submit_directory' etc.)

For example, the following image is the set of hyper-parameters for the job when we give it as part of TrainingStep:
<img width="645" alt="Screenshot 2020-08-04 at 6 21 42 PM" src="https://user-images.githubusercontent.com/12937657/89296055-7b892e80-d67f-11ea-8b3b-f8a419aca847.png">

But, if we give the hyper-parameters as part of the estimator: 
<img width="1029" alt="Screenshot 2020-08-04 at 6 12 59 PM" src="https://user-images.githubusercontent.com/12937657/89295741-07e72180-d67f-11ea-824e-e381444bac00.png">

The reason why I'd want to give hyper-parameters as part of the TrainingStep is that I'd be able to use `stepfunctions.inputs.ExecutionInput` in order to provide inputs dynamically that might be useful in the script.

**Comment by shivlaks** [comment]
fixed through #144 which enables the capability to specify hyperparameters in the TrainingStep constructor and merges them with hyperparameters established in the estimator.
