### ISSUE TITLE
Support for passing full arn to LambdaStep on init

### ISSUE THREAD

**Issue by andydouglas-exs** [aws/aws-step-functions-data-science-sdk-python#8]
Hi

My understanding is that the result returned from a Lambda varies dependent on whether the full arn is passed or the shortened one. For example, if the resource is `arn:aws:states:::lambda:invoke` and the function name is passed in the payload then the result of the lambda will also be in a payload field, which then requires unpacking. 

If the full arn is specified then the result is returned directly. Therefore, it would be good if when the full arn is passed to the Lambda Step as a kwarg arg, it is preserved not clobbered.

Thanks
Andy

**Comment by shunjd** [comment]
Hi Andy,

There are two ways of connecting Lambda function in AWS Step Functions. You can use specify the `resource` field in a `Task` object, or using the `LambdaStep` with parameters contain the `FunctionName`. If you are use the `arn:aws:states:::lambda:invoke`, you do have more options to invoke the Lambda function compared to just setting the Lambda arn into the `resource` field.

Doc: https://docs.aws.amazon.com/step-functions/latest/dg/connect-lambda.html

Thanks,
Shunjia

**Comment by andydouglas-exs** [comment]
Hi Shunjia

Thanks for your response. Yes, agreed there are 2 ways but using the full arn strips out a number of (normally) superfluous fields from the lambda result including the log which can be quite large (and "LogType": None doesn't seem to work). Commonly, I want to preserve the input and the payload but nothing else from the lambda result. If you know of a way to do this with using arn:aws:states:::lambda:invoke please say, as it would be very useful!

Andy

**Comment by shunjd** [comment]
Hi Andy,

Yes, you can do that using the `LambdaStep` with the `output_path` parameter. That will make the output looks exactly like the other lambda call.

```python
lambda_step = steps.LambdaStep(parameters={
    'FunctionName': 'YourLambdaFunction',
}, output_path='$.Payload')
```

Doc: https://docs.aws.amazon.com/step-functions/latest/dg/concepts-input-output-filtering.html

Shunjia

**Comment by andydouglas-exs** [comment]
Hi Shunjia

But then you lose the input?

Andy

**Comment by shunjd** [comment]
Hi Andy,

If you want to preserve the input, you cannot do it within a single Lambda state. There is a workaround if you want to achieve this.

```python
lambda_step = steps.LambdaStep(parameters={
    'FunctionName': 'YourLambdaFunctionName'
}, result_path='$.LambdaOutput')

merge_input_output_step = steps.Pass(input_path='$.LambdaOutput.Payload', result_path='$.LambdaOutput')

lambda_step.next(merge_input_output_step)
```

Basically, in the Lambda step, we use `result_path` to merge the Lambda result into the input under the key `LambdaOutput` and pass it down to next step. In the Pass step, we pick up the the value from `$.LambdaOutput.Payload` and use it to overwrite the value of `LambdaOutput`.

Shunjia

**Comment by andydouglas-exs** [comment]
That's neat. I still feel having the option to use the full arn would make sense in order to avoid having to do the above, but thanks for the workaround
