### ISSUE TITLE
Can't define OutputDataConfig for TrainingStep 

### ISSUE THREAD

**Issue by szamarin** [aws/aws-step-functions-data-science-sdk-python#80]
It doesn't look like it's possible to specify the output path for the model artifacts in the TrainingStep class. You can only use the default output directory or define it in the estimator object before you pass it to the TrainingStep. In either case it doesn't look like its possible to set the output path from the execution input or the output of a prior task.

**Comment by a13zen** [comment]
+1 on this. 

One could potentially work around this by overwriting the sagemaker default bucket (https://github.com/aws/sagemaker-python-sdk/issues/1402), but this doesn't allow you to specify a path, only a different bucket.

As the API integration supports creating the OutputDataConfig (https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html), it makes sense to expose it via this SDK directly.

**Comment by shivlaks** [comment]
Implemented in  #142  which has now been merged 🎉
