### ISSUE TITLE
Feature request: support placeholders in the data parameter of TrainingStep constructor

### ISSUE THREAD

**Issue by lucaboulard** [aws/aws-step-functions-data-science-sdk-python#97]
Currently the `data` parameter to the `TrainingStep` constructor does not support placeholders, requiring the s3 location of the dataset to be known at workflow creation time.
It would be useful for this parameter to accept dynamic s3 uri, via placeholders.

**Comment by shivlaks** [comment]
Implemented in  #142  which has now been merged 🎉
