### ISSUE TITLE
Feature request: adding output_path parameter to TrainingStep constructor

### ISSUE THREAD

**Issue by lucaboulard** [aws/aws-step-functions-data-science-sdk-python#98]
Currently it is not possible to specify the output path to TrainingStep. The one specified to the wrapped estimator counts. But estimartos does not support placeholders, so the output path must be known at workflow creation time.
It would be useful to be able to specify a dynamic output path to the TrainingStep using placeholders, overriding the estimator output_path .

**Comment by ca-nguyen** [comment]
Hello Luca, 
Thank you for this feature request!
Starting work on a PR to support the use of dynamic output_path for TrainingStep - it will be published in the following days.
